### ISSUE TITLE
Green datepicker input field issues

### ISSUE THREAD

**Issue by viliusmac** [sebgroup/green#1174]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

datepicker

### Description

1. You can input numbers like "2024-01-123412341234" and only after clicking away it corrects itself. It should be limited to yyyy-mm-dd.
![image-2024-01-24-17-24-49-334](https://github.com/sebgroup/green/assets/35391478/1a23e643-8759-47ff-aa0b-86dc939a3a62)

3. If you limit the earliest possible date (for ex. max 5y.) you can still input the text field dates like "2019-01-01" (more than five years). It shows an error, but doesn't correct itself to the earliest possible day as it should. 
![image-2024-01-24-17-23-58-624](https://github.com/sebgroup/green/assets/35391478/095bfca2-1fe4-49c0-a2f4-f4ef6083ecbf)

### Steps To Reproduce

1. Input via keyboard "2024-01-123412341234".
----------------------------------------------------
1.  Limit the earliest previous date to max 5 years.
2.  Input "2019-01-01" via keyboard and click away.

### Current Behaviour

Days in date can take a longer than DD input. Date doesn't correct itself if the date is earlier than set limit if the year and month is correct and the day is altered manually via keyboard.

### Expected Behaviour

1. Should limit input field to YYYY-MM-DD.
2. Should correct itself if manually written date surpasses the set earliest limit instead of just showing an error underline.

**Comment by splashdust** [comment]
@viliusmac Thanks for creating an issue. A fix is underway in #1176

The second point is actually the correct behaviour as is. As a user, you should be able to enter dates outside of the range and receive and error message. Otherwise, chances are that you don't notice or realise the field "autocorrected" and you end up submitting something else than you expected.

If you really need to autocorrect the field, you can always do it on the application side.
