### ISSUE TITLE
Datepicker: Incorrect date when selecting older dates in reactive forms

### ISSUE THREAD

**Issue by sixskulls** [sebgroup/green#1227]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

datepicker

### Description

When using in reactive form datepicker value is incorrect when you select a previous date.

### Steps To Reproduce

1. In https://sebgroup.github.io/green/latest/angular/?path=/docs/components-datepicker--form
2. Select previous date in same month
3. See wrong date output in form value 
![image](https://github.com/sebgroup/green/assets/33746492/aef35392-d54b-4be3-8e9f-00c508f97b49)

### Current Behaviour

Form values returns previous day 22:00, instead of selected date. 

### Expected Behaviour

When selecting a specific date getting same date value in the form value.

**Comment by splashdust** [comment]
@sixskulls The Datepicker emits a javascript `Date` object set to 00:00 of the selected date in local time. What you're seeing on the Storybook page is the ISO 8601 representation of that date in UTC offset (the Z at the end means UTC). So if you are on CET, for example, the ISO date will show -2 hours, which in this case will be 22:00 of the previous date.

It might make more sense for the Datepicker to set the time to 12:00 instead of 00:00, so that the date is the same in all time zones. I will look into it!

**Comment by sixskulls** [comment]
Makes sense, I was wondering what I was missing. Feel free to close, we can adjust accordingly on our side.

**Comment by splashdust** [comment]
Closing this one, but opened related #1250
