### ISSUE TITLE
Documentation on how to use green properly in angular libraries/components

### ISSUE THREAD

**Issue by mackelito** [sebgroup/green#1353]
### Description

It would be really nice to have clear docs on how we should use green when creating custom components in angular features/standalone components.

**Comment by splashdust** [comment]
While we're working on improving the docs, here's some additional information on how to use Green Core with different frameworks: https://github.com/sebgroup/green/tree/main/libs/core#using-angular

Also, you can have a look at how we're using it in the Green Angular components that are currently wrapping web components. Currently [dropdown](https://github.com/sebgroup/green/tree/main/libs/angular/src/lib/dropdown), [datepicker](https://github.com/sebgroup/green/tree/main/libs/angular/src/lib/datepicker) and [context menu](https://github.com/sebgroup/green/tree/main/libs/angular/src/lib/context-menu) are doing this.

**Comment by mackelito** [comment]
How do you recommend adding stying to eg. UI components?
Let's say I have a list of items and want to use the Grouped list component.

Adding it as instructed here "https://github.com/sebgroup/green/tree/main/libs/core#using-angular" will not provide the proper styles for the component and the app might not include the green design lib.. :)

**Comment by splashdust** [comment]
The web components in Green Core are stand-alone in the sense that they encapsulate styling in Shadow DOM.

There is one caveat though: CSS variables. Since the components are mainly expected to be used in existing Chlorophyll based applications, they depend on the CSS variables defined by Chlorophyll. Since those are added on `:root`, and CSS variables permeate Shadow DOM boundaries, they are inherited into the components. But if Chlorophyll is not added on the page, components will look broken.

We have a work-around for this. There's a component called `<gds-theme>` which adds these variables locally. It's used like this:

```html
<gds-theme>
  <!-- Use any gds-component in here and it will have access to correct CSS variables -->
</gds-theme>
```

It's available in the lib now, but not quite finished yet, and not documented, so use with care. Eventually, this component will also be used to control dark-mode settings for its children.

**Comment by mackelito** [comment]
hmm.. tried it like this

```
<gds-theme>
  <gds-grouped-list *nggCoreElement>
    <gds-list-item *nggCoreElement
      ><div>Item 1</div>
      <strong>asd</strong>
    </gds-list-item>
    <gds-list-item *nggCoreElement>Item 2</gds-list-item>
    <gds-list-item *nggCoreElement>Item 3</gds-list-item>
  </gds-grouped-list>
</gds-theme>

  <gds-grouped-list *nggCoreElement>
    <gds-list-item *nggCoreElement
      ><div>Item 1</div>
      <strong>asd</strong>
    </gds-list-item>
    <gds-list-item *nggCoreElement>Item 2</gds-list-item>
    <gds-list-item *nggCoreElement>Item 3</gds-list-item>
  </gds-grouped-list>
````
but they both looked the same (not properly styled)

**Comment by splashdust** [comment]
You need the `*nggCoreElement` directive on the `<gds-theme>` component as well.

**Comment by mackelito** [comment]
Still no styling when adding *nggCoreElement
Is there anything else needed to get styles?

**Comment by mackelito** [comment]
also.. jest test are not working..
https://github.com/sebgroup/green/issues/952

**Comment by mackelito** [comment]
It's a shame, but all of these issues that keeps popping up forces us to go with chlorophyll instead. I know that you do not recommend it but for us it's not viable right now. :(

**Comment by mackelito** [comment]
There are other things styled as well... spacings, paddings, line-heights etc etc.. 
We are already on the latest version but still not working.

I switched to use chlorophyll instead :/
