### ISSUE TITLE
list should follow rules of semantic HTML

### ISSUE THREAD

**Issue by mario-subo** [sebgroup/green#315]
<img width="613" alt="Screenshot 2022-01-11 at 4 09 49 PM" src="https://user-images.githubusercontent.com/49055952/148904679-589883eb-2ef9-480f-a72f-89c426861c97.png">

https://sebgroup.github.io/green/latest/chlorophyll/?path=/story/components-list-ordered--page

### The HTML structure of the list example should be re-examined to make sure `div` elements are not inside the a `dl` element for example
<img width="808" alt="Screenshot 2022-01-11 at 4 11 14 PM" src="https://user-images.githubusercontent.com/49055952/148904992-22adf329-b916-4071-a3aa-4fbb4fbd71ed.png">

https://www.w3resource.com/html/definition-lists/HTML-definition-lists-dl-dt-dd-tags-elements.php

**Comment by hjalmers** [comment]
@mario-subo I think that's an old specification as nesting `dt` and `dd` elements in `divs` within `dl` elements is actually valid and correct html since a few years back and it's still valid according to [WHATWG](https://whatwg.org/) and the latest specifications:

https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#wrapping_name-value_groups_in_div_elements

However there's another issue with the example as I seem to have mixed up the `dd` tags and with `dl` tags which definitely  isn't valid 😱 so I'll make sure that's corrected 😃
