### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by JohanObrink** [sebgroup/green#333]
**Features:**

- [x] Markup and CSS
- [x] Common logic in Extract with ability to set and select a date etc.
- [x] Ability to define when week starts (defaults to monday)
- [x] Custom style for holidays, disabled dates and today
- [x] Month and year selector with support for custom year range
- [x] Automatic datepicker placement using popper.js
- [ ] Ability to set min and max date
- [ ] Show week numbers
- [ ] Custom container for datepicker (when used together with component with overflow hidden/auto)
- [ ] Prevent scroll in background using body scroll lock
- [ ] Disable specific dates and holidays
- [ ] Optimise for mobile (adjust position and animation)
- [ ] Keyboard navigation
- [ ] Close on outside click
- [ ] Range select (separate issue)

This component is currently the most requested. I think the way to implement it is this:

1. Define HTML and CSS in Chlorophyll
2. Copy and, if necessary, modify the tests for the current implementations in Angular and React
  - https://github.com/sebgroup/ng-components/blob/develop/projects/ng-components/lib/datepicker/datepicker.component.spec.ts
  - https://github.com/sebgroup/react-components/blob/develop/lib/src/Datepicker/Datepicker.test.tsx
3. Copy the implementations from ng-components/react-components into green
  - https://github.com/sebgroup/ng-components/tree/develop/projects/ng-components/lib/datepicker
  - https://github.com/sebgroup/react-components/tree/develop/lib/src/Datepicker
4. Get tests working
5. Agree on and implement any interface changes
6. Release
7. Refactor all common logic into extract and clean up the implementation
8. Release again

**Comment by JohanObrink** [comment]
Or maybe we just wrap [Duet Date Picker](https://github.com/duetds/date-picker#duet-date-picker)? It's recommended by [DigitalA11y](https://www.digitala11y.com/), easily styleable through css variables and built as a WebComponent with documentation on how to wrap in Angular and React.

**Comment by hjalmers** [comment]
@JohanObrink I think the latter is a better option, especially since the components provided by our own existing react and angular libs use native datepickers which we previously have said that we don't want to use. We use other components for angular but I think it would be hard to use them in a nice way with green so I'd also propose building on top of a framework independent implementation. Duet seems like a good candidate, at least for basic datepickers but it lacks some of the features and the behaviour differs from what we've defined in Figma😕 

I think we need to compromise a bit in terms of UI and behaviour unless we want to build something from scratch. @splashdust, you created css for a custom datepicker for vanilla right, did you or anyone else write logic for it too?

**Comment by JohanObrink** [comment]
Alternative: https://litepicker.com/

**Comment by JohanObrink** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/548783/158959767-7d94e2d3-0c99-47b9-a9a6-f80f474c76c3.png">

@hjalmers When the month is wider, the component gets stretched. Should we truncate the dropdown or just center the calendar?

**Comment by JohanObrink** [comment]
Also... maybe add css transitions so it animates smoothly instead of jerking from side to side?

**Comment by hjalmers** [comment]
@JohanObrink missed this but the size issue with longer months has been addressed:) Transitions and animations remain though...
