### ISSUE TITLE
Dropdown: include all required css

### ISSUE THREAD

**Issue by Maximilian-R** [sebgroup/green#448]
When mixing frameworks it would simplify if each component `@use` everything needed for it - then it's a simple step to `@import` the required component with only one import.

Currently required for using only the dropdown:
```
@use '@sebgroup/chlorophyll/scss/components/use-green-scope';
.use-green {
  @import '@sebgroup/chlorophyll/scss/components/dropdown';
  @import '@sebgroup/chlorophyll/scss/components/list';
  @import '@sebgroup/chlorophyll/scss/components/close';
  @import '@sebgroup/chlorophyll/scss/components/utility';
}
```

After change:
```
@use '@sebgroup/chlorophyll/scss/components/use-green-scope';
.use-green {
  @import '@sebgroup/chlorophyll/scss/components/dropdown';
}
```

We also need to check if the same css is included twice when two components are imported with `@import` but internally they are importing with `@use`

**Comment by hjalmers** [comment]
@Maximilian-R our assumption seems to be valid, using multiple @use together with @import won't result in code duplication as long as we're only importing a component or sass module once using `@import`. I've updated the documentation to reflect this so instead of doing multiple imports like this:

```scss
// styles.scss
.use-green {
  @import '@sebgroup/chlorophyll/scss/components/button';
  @import '@sebgroup/chlorophyll/scss/components/list';
  @import '@sebgroup/chlorophyll/scss/components/dropdown';
}
```

We should only `@import` a single file that can include multiple components with `@use`

```scss
// styles.scss
.use-green {
  @import 'custom-green';
}

// custom-green.scss
@use '@sebgroup/chlorophyll/scss/components/button';
@use '@sebgroup/chlorophyll/scss/components/list';
@use '@sebgroup/chlorophyll/scss/components/dropdown';
```

The example above would only generate the code for list once under `.use-green` even though it's being referenced twice (once directly using list and  then again by including dropdown which has a dependency to list).
