### ISSUE TITLE
Release Strategy

### ISSUE THREAD

**Issue by vsjolander** [sebgroup/green#596]
How should the release strategy be for our packages in Green?

- How is it handled with Github Actions and NX?

**Comment by splashdust** [comment]
### Some thoughts on how a release strategy for Green could look

* The `main` branch should always contain tested, reviewed and releasable code.

* Every merge to `main` should automatically produce pre-release packages. These would have a version format like `1.2.3-pre.4`. The three first numbers will be indicative of what version the next production release will have. In this example the last production release was `1.2.2` and the next will be `1.2.3`. These pre-releases are intended for additional testing or when a consumer need immediate access to some new feature or bug fix. Pre-releases should *probably* not update the change-log.

* In addition to pre-releases, merges to `main` should trigger an action that opens a "Cut release" pull request, or updates an existing one if one is already open. This pull request would serve as a preview of the next release, and contain a text summary of all that will change (basically the change-log), as well as the commits that will update the `CHANGELOG.MD` files. This would give us an opportunity to tweak the content of the change logs if necessary. When the "Cut release" PR is merged to `main`, a new production release will be triggered automatically.
Ideally, this PR should be "squashed and merged" to avoid having multiple commits for all the change log updates.

* Production releases should tag the commit produced from merging the "Cut release" PR to the `main` branch. Each released project will have a separate tag.

* It is assumed that each project is versioned separately, and that sub-dependencies within Green will be bumped automatically.

### Benefits
This strategy allows for immediate access to new features and bug fixes when necessary, while also avoiding to "spam" the change-logs with lots of single-fix patch releases. We could use the "daily" meeting every Tuesday to merge the next "Cut release" PR and thereby create a new production release once a week.

### Breaking changes
One thing that it *doesn't* solve is how to deal with breaking changes. The "Cut release" PR will not make it possible to do any sort of cherry-picking, since all the code will already be in the `main` branch.

I think breaking changes need to be dealt with on a pull request basis. When reviewing a pull request, one needs to pay extra attention to breaking changes and help the author make sure they are marked as such. And perhaps we can add some labelling automation that checks the commits in a PR for `BRAKING CHANGE` and adds a label to it.

Then we could allow breaking changes to accumulate over a month, or a few months, and do larger releases every once in a while. Breaking pull requests could possibly produce another variant of pre-release packages, something like `1.2.3-pr123.0`, to assist with testing these breaking changes in applications before final release.

### Conclusion
These are just some ideas I've been thinking about, and it might no be possible, or desirable, to implement all of it, but perhaps this can serve as a basis for discussion.

Also, feel free to obliterate these ideas with your arguments :)

Cheers!

**Comment by splashdust** [comment]
Great news! Looks like GitHub has solved at least some of this for us!

https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/#:~:text=Merge%20queue%20helps%20increase%20velocity,the%20main%20branch%20when%20merged.

If I've understood correctly, Merge Queues would allow us to queue up pull requests and merge several of them at the same time. This means that we can have automatic releases from the main branch without spamming out a bunch of new releases when merging multiple PRs.

Merge Queues should essentially remove the need for the "Cut Release" automatic pull requests that I suggested in the previous post.
