### ISSUE TITLE
Dropdown: qa-data attribut

### ISSUE THREAD

**Issue by Maximilian-R** [sebgroup/green#613]
Dropdown option `<label />` & `<input/>` elements are not possible to identify without checking the inner HTML, which is not convenient when trying to identify an option with test-scripts

Solution: add qa-data attributes

**Comment by splashdust** [comment]
Closing this issue, since both the problem and solution are likely different with the new Core dropdown.

In the new dropdown, the options are represented by `<gds-option>` elements. So if the consumer wants to add qa-hooks, or other ways to target these, they can. Since these elements are slotted, they can be queried and selected like regular DOM nodes.

So, an application that have special QA/testing needs might do something like:
```html
<gds-dropdown>
  <gds-option data-qa='qa-option-1'>Option 1</gds-option>
  <gds-option>Option 2</gds-option>
  <gds-option>Option 3</gds-option>
</gds-dropdown>
```

They can then easily single out that option by:
```js
const opt = document.querySelector('[data-qa=qa-option-1]')
```
