### ISSUE TITLE
Issue with "legend" tag on IBP

### ISSUE THREAD

**Issue by antonseb** [sebgroup/green#635]
We use Green in our MFE on IBP and have an issue with divider lines showing up when we use <legend> tag. These divider lines are not visible outside IBP. See below screenshot:
![image](https://user-images.githubusercontent.com/117288898/199513343-38088bcc-b1a5-42c1-97d4-ca71d6bad557.png)

Link: https://apps.dev.sebank.se/cps/ibp/wow/3000/3500/wow3564.aspx?context=ibp

**Comment by vsjolander** [comment]
Seems that you have some leaking styles. I don't think that this is not a part of Green and since this is not a part of Green it's hard to make a fix especially when it's a lot of rules that are marked with !important.

One way would be to make a "!important reset" within Green that you use in special scenarios like working in IBP. But don't like that solution really..

**Comment by daneriseb** [comment]
This can be closed. I have fixed this in our repo in a "ibp-reset.scss" file. I didn't need to use !important, I used "inherit" instead.
