### ISSUE TITLE
Wrong dependency version in Changelog when updated with @jscutlery/semver.

### ISSUE THREAD

**Issue by vsjolander** [sebgroup/green#726]
Seems like @jscutlery/semver has problems with writing the right dependency version in the change log.

**Comment by splashdust** [comment]
It might be worth having another go at semver, there has been a lot of activity there since the version we're currently using: https://github.com/jscutlery/semver/releases

Otherwise, here are some alternatives we could have a look at instead of semver:
* https://github.com/TheUnderScorer/nx-semantic-release
* https://semantic-release-plus.gitbook.io/semantic-release-plus/
