### ISSUE TITLE
Icons: Component can't be imported

### ISSUE THREAD

**Issue by aurimasvarnelis** [sebgroup/green#894]
### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

Icons

### Description

Cannot import icons from the lib folder [here](https://github.com/sebgroup/green/tree/main/libs/react/src/lib/icons), because it lacks export [here](https://github.com/sebgroup/green/blob/main/libs/react/src/index.ts)

**Comment by splashdust** [comment]
These are currently not part of the public API, and the way we work with icons will change in the near future, so for the moment these are only for internal use by the framework itself.

In the mean time, you can use FontAwesome Pro for icons. Check the link at bottom here for instructions on how to get access to FA Pro: https://designlibrary.sebgroup.com/foundation/digital-design/visual-identity/icons/

That said, though, missing exports have turned out to be a quite common issue in our setup lately, and our current test setup doesn't catch those, so keep reporting! :)
