### ISSUE TITLE
Dropdown popover z-index 

### ISSUE THREAD

**Issue by prasunakaveti** [sebgroup/green#955]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

dropdown

### Description

We need to fix the z- index of the dropdown so that the popover can be visible when it is expanded toward top in the Business Area.
Or make popover position down to avoid the issue?

![Business_Arean_tst_env](https://github.com/sebgroup/green/assets/46931434/24106f22-aec5-4373-be79-6cc866bfe487)

**Comment by splashdust** [comment]
@prasunakaveti Hey, can you try increasing the value of the CSS variable `--sg-z-index-dropdown` ?
You can simply try it in dev tools, just search for the variable name. If that works, we can set the new higher value as default in Green.

If it doesn't work, try adding some margin to the bottom of your app, in order to pad out the height of the page. The dropdown opens upwards because there isn't enough space downwards. This could work as a temporary workaround.
The Dropdown component is currently getting a major overhaul, and that will include new positioning logic for the popover, but it is probably a few weeks away.

Let me know if one of these suggestions works!
